pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    headerLogo:
                        items:
                            -
                                method: resize
                                arguments:
                                    width: 100
                                    height: 100
                        medias: {  }
                        name: headerLogo
                        description: ''
                        group: ''
                        format: PNG
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1655468043
                        creationDate: 1655466741
                        preserveAnimation: false
